djangoOrderVan/OrderVan/urls.py
from django.conf.urls import url

from . import views

app_name = 'OrderVan'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # Orders urls
    url(r'^orders/?$', views.OrdersResultsView.as_view(), name='order_results'),

    # The () "capture" the result of regex.
    # The ?P<X> is the name og the kwarg
    # The trailing /? is for it to work with trailing slash or without
    url(r'^orders/(?P<pk>[0-9]+)/details/?$', views.OrdersDetailView.as_view(), name='order_details'),
    url(r'^orders/(?P<order_id>[0-9]+)/change_status/?$', views.change_order_status, name='change_order_status'),
    url(r'^orders/new_order/?$', views.NewOrder.as_view(), name='new_order'),

    # Vendors urls
    # url(r'^vendors/(?P<vendor_id>[0-9]+)/$', views.vendor_details, name='vendor_details'),
    # url(r'vendors$', views.all_vendors, name='all_vendors'),

]

djangoOrderVan/djangoOrderVan/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^OrderVan/', include('OrderVan.urls')),
    url(r'^admin/', admin.site.urls),

    # Authentication
    url(r'^login/?$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/?$', auth_views.logout, {'next_page': 'OrderVan/'}, name='logout'),

]

djangoOrderVan/OrderVan/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User, AnonymousUser
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Project(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class ProjectCategory(models.Model):
    class Meta:
        verbose_name_plural = "project categories"

    name = models.CharField(max_length=100)
    father_project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Manager(models.Model):
    user = models.ForeignKey(User)

    def __str__(self):
        return self.user.username


@python_2_unicode_compatible
class Vendor(models.Model):
    name = models.CharField(max_length=200)

    def is_military(self):
        return self.name in ["Raphael", "MAFAT"]

    @property
    def most_expensive_purchase(self):
        # order_set is auto generated by django because of the ForeignKey relationship
        # Of Course this is wrong - because we don't take currency into account
        return self.order_set.order_by("price")[0]

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class VendorContact(models.Model):
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    contact_mail = models.CharField(max_length=200)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Order(models.Model):
    CURRENCIES = [
        ("USD", "Dollar"),
        ("EU", "Euro"),
        ("NIS", "Shekel")
    ]

    GENERAL_STATUSES = [
        # ("Committed", "Committed"),
        # ("ManagerApproved", "Approved by project manager"),
        # ("CEOApproved", "Approved by CEO"),
        # ("FinanceApproved", "Approved by finances"),
        ("AwaitingApproval", "Awaiting Approval"),
        ("Approved", "Approved"),
        ("ContactConfirmed", "Confirmed Contact "),
        ("Sent", "Order Sent"),
        ("ReceivedProduct", "Product Received"),
        ("ProductOK", "Product is OK"),
        ("ApprovedForPayment", "Approved For Payment"),
        ("Paid", "Paid"),
        ("ReceivedStock", "Received Stock"),
    ]

    URGENCIES = [
        ("Today", "Today"),
        ("Tommorow", "Tommorow"),
        ("This Week", "This Week")
    ]

    # Fill upon creation
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    order_information = models.CharField(max_length=300)

    created_by = models.ForeignKey(User, editable=False)

    # the param is a human readable name for column
    pub_date = models.DateTimeField('date published', auto_now=True)

    urgency = models.CharField(max_length=10, choices=URGENCIES)

    # Each Order is related to a single vendor..
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    vendor_contact = models.ForeignKey(VendorContact, on_delete=models.CASCADE)

    price = models.PositiveIntegerField()
    currency = models.CharField(max_length=3, choices=CURRENCIES)

    quote = models.FileField(default="", upload_to=".", blank=True, null=True)
    drawing = models.FileField(default="", upload_to=".", blank=True, null=True)

    project = models.ForeignKey(Project)
    project_category = models.ForeignKey(ProjectCategory)
    percentage = models.PositiveIntegerField()

    manager = models.ForeignKey(Manager, editable=True, related_name="manage_user")

    needs_insurance = models.BooleanField(default=False)
    needs_end_user = models.BooleanField(default=False)
    end_user_file = models.FileField(upload_to=".", blank=True, null=True)
    needs_afp = models.BooleanField(default=False)

    # Approval round
    manager_approved = models.BooleanField(blank=True, default=False)
    ceo_approved = models.BooleanField(blank=True, default=False)
    finance_approved = models.BooleanField(blank=True, default=False)

    # Before actual sending

    # Tracking status against vendor
    date_sent_order = models.DateField(blank=True, null=True)
    estimated_delivery = models.DateField(blank=True, null=True)
    receipt_date = models.DateField(blank=True, null=True)

    general_status = models.CharField(max_length=20, choices=GENERAL_STATUSES, default="Committed")

    def __str__(self):
        return self.title[:15] + "..."

djangoOrderVan/OrderVan/forms.py
from django.forms import ModelForm, Textarea, Form, ChoiceField, CharField, SelectDateWidget
from models import Order


class NewOrderForm(ModelForm):

    class Meta:
        model = Order
        fields = ["title", "description", "vendor", "price", "currency", "manager", "quote"]
        widgets = {
            'description': Textarea(attrs={'rows': 10})
        }

    def __init__(self, *args, **kwargs):
        super(NewOrderForm, self).__init__(*args, **kwargs)
        self.fields['quote'].required = False


class OrderDetailsForm(ModelForm):

    class Meta:
        model = Order
        fields = "__all__"
        widgets = {
            'date_sent_order': SelectDateWidget,
            'estimated_delivery': SelectDateWidget,
            'receipt_date': SelectDateWidget
        }


class SearchForm(Form):

    filter_by_status = ChoiceField(choices=Order.GENERAL_STATUSES,
                                   required=False, widget=None, label="Filter By General Status")

    fields_to_filter = [(f.name, f.name) for f in Order._meta.get_fields()]
    orderby = ChoiceField(required=False, choices=fields_to_filter)

djangoOrderVan/OrderVan/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.views.generic.edit import CreateView
from django.utils import timezone

import forms
from .models import Vendor, Order


# View for homepage
def index(request):
    latest_orders = Order.objects.order_by("pub_date")[:5]

    context = {
        'latest_orders': latest_orders,
    }

    return render(request, "OrderVan/index.html", context)


class OrdersResultsView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'orderVan/order_results.html'
    context_object_name = "latest_orders"
    paginate_by = 10

    def get_queryset(self):
        orderby = self.request.GET.get("orderby", '-pub_date')
        filter_val = self.request.GET.get('filter_by_status', None)

        orders = Order.objects.all()
        if filter_val:
            orders = orders.filter(general_status=filter_val)
        orders = orders.order_by(orderby)
        return orders

    def get_context_data(self, **kwargs):
        context = super(OrdersResultsView, self).get_context_data(**kwargs)
        context['form'] = forms.SearchForm

        return context


class OrdersDetailView(LoginRequiredMixin, generic.UpdateView):
    model = Order
    template_name = 'orderVan/order_details.html'

    # context_object_name is implicitly given to be "order"

    def get_form_class(self):
        return forms.OrderDetailsForm


class NewOrder(LoginRequiredMixin, CreateView):
    model = Order
    fields = "__all__"
    template_name = 'orderVan/new_order.html'
    # Need to reverse lazy because this will be run before the url conf is loaded
    success_url = reverse_lazy('OrderVan:order_results')

    def form_invalid(self, form):
        response = super(NewOrder, self).form_invalid(form)
        return response

    def form_valid(self, form):
        order = form.save(commit=False)
        order.pub_date = timezone.now()
        order.created_by = self.request.user
        order.save()
        response = super(NewOrder, self).form_valid(form)
        return response

    def get_form_class(self):
        return forms.NewOrderForm


def change_order_status(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    try:
        order.general_status = Order.GENERAL_STATUSES[int(request.POST["general_status"]) - 1][1]
        print("changing general status: ", order.general_status)
    except (KeyError, Order.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'OrderVan/change_order_status.html', {
            'order': order,
            'error_message': "You didn't select a choice.",
        })

    order.save()

    return HttpResponseRedirect(reverse('OrderVan:order_details', args=(order.id,)))

djangoOrderVan/OrderVan/templates/OrderVan/change_order_status.html
{% extends "base.html" %}

{% block title %}OrderVan Home{% endblock %}


{% block content %}

<h1>{{ order.description }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'OrderVan:change_order_status' order.id %}" method="post">
{% csrf_token %}
{% for status in order.GENERAL_STATUSES %}
    <!-- name means the POST will have in it general_status=id -->
    <input type="radio" name="general_status" id="general_status{{ forloop.counter }}" value="{{ forloop.counter }}" />
    <label for="general_status{{ forloop.counter }}">{{ status }}</label><br />
{% endfor %}
<input type="submit" value="Submit Here!" />
</form>

{% endblock %}

djangoOrderVan/OrderVan/templates/OrderVan/index.html
{% extends "base.html" %}

{% block title %}OrderVan Home{% endblock %}


{% block content %}

    <div class="jumbotron">
        <h1>OrderVan</h1>
        <p>Civan Order Management Site.</p>
    </div>

{% endblock %}

djangoOrderVan/OrderVan/templates/OrderVan/new_order.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %} New Order {% endblock %}


{% block content %}

<form action="{% url 'OrderVan:new_order' %}" method="post" class="form" enctype="multipart/form-data" >
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Submit
    </button>
  {% endbuttons %}
</form>

<!--
<form enctype="multipart/form-data" action="{% url 'OrderVan:new_order' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    <input type="submit" value="save" />
</form>
-->
{% endblock %}

djangoOrderVan/OrderVan/templates/OrderVan/order_details.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %} Order Details {% endblock %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Update" />
</form>

<!--div>{{ order }}</div>
<div>{{ order.general_status }}</div>
<div><a href="{% url 'OrderVan:change_order_status' order.id %}">Change General Status</a></div-->

{% endblock %}

djangoOrderVan/OrderVan/templates/OrderVan/order_results.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block title %} Order Results {% endblock %}


{% block content %}

<form action="{% url 'OrderVan:order_results' %}" method="get" class="form-vertical" enctype="multipart/form-data" >

    <!-- Can't use normal bootstrap_form tag like in new_order because i want the fields vertical, see issue on github at: https://github.com/dyve/django-bootstrap3/issues/296-->
    <div class="row">
        <div class="col-md-4">
          {%  bootstrap_field form.filter_by_status %}
        </div>
        <div class="col-md-4">
          {%  bootstrap_field form.orderby %}
        </div>
        <div class="col-md-4" style="">
          {% buttons %}
            <!-- top margin is ugly patch so button will be inline with boxes and not with label. -->
            <button type="submit" class="btn btn-primary" style="margin-top:25px">
                {% bootstrap_icon "star" %} Filter
            </button>
          {% endbuttons %}
        </div>
    </div>

</form>

{% if latest_orders %}

	<div class="row">
	  <div class="col-md-12">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Order Maker</th>
                <th>Title</th>
                <th>Price</th>
                <th>Manager</th>
                <th>Status</th>
                <th>Details</th>
              </tr>
            </thead>
            <tbody>
            {% for order in latest_orders %}
                  <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.created_by }}</td>
                    <td>{{ order.title }}</td>
                    <td>{{ order.price }} {{ order.currency }}</td>
                    <td>{{ order.manager }}</td>
                    <td>{{ order.get_general_status_display }}</td>
                    <td><a href="{% url 'OrderVan:order_details' order.id %}">details</a></td>
                  </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
	</div>


{% else %}
    <p>No orders are available.</p>
{% endif %}

<!-- copied from https://simpleisbetterthancomplex.com/tutorial/2016/08/03/how-to-paginate-with-django.html -->
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}